/** Route list for the tests, mirroring lib/routes.ts without importing app code. */
export const PUBLIC_ROUTES = [
  "/",
  "/how-it-works",
  "/demo",
  "/pricing",
  "/resources",
  "/contact",
  "/privacy",
  "/terms",
  "/thank-you",
  "/features/recall-and-forward-trace",
  "/features/process-data-capture",
  "/features/part-genealogy",
  "/features/marking-and-labels",
  "/features/offline-first-stations",
  "/features/audit-and-tamper-evidence",
  "/features/route-configuration",
  "/features/deployment-and-updates",
  "/industries/auto-components",
  "/industries/pumps-and-valves",
  "/industries/switchgear-and-electricals",
  "/industries/ev-components",
  "/industries/precision-machining",
  "/industries/general-assembly",
  "/vs/siemens-opcenter",
  "/vs/sepasoft-mes",
  "/vs/delmiaworks",
  "/vs/itac",
  "/vs/aidc-integrators",
  "/resources/traceability-requirements-iatf-16949-audit",
  "/resources/capturing-torque-data-from-a-plc",
  "/resources/what-a-part-genealogy-record-must-contain",
  "/resources/laser-marking-vs-label-printing",
  "/resources/planning-a-recall-scope-calculation",
  "/resources/mes-or-standalone-traceability",
] as const;
