export type Block =
  | { type: "p"; text: string }
  | { type: "h2"; text: string }
  | { type: "h3"; text: string }
  | { type: "ul"; items: string[] }
  | { type: "ol"; items: string[] }
  | { type: "note"; text: string }
  | { type: "table"; caption: string; head: string[]; rows: string[][] }
  | { type: "code"; caption: string; lines: string[] };

export type Resource = {
  slug: string;
  title: string;
  metaTitle: string;
  description: string;
  published: string;
  readingMinutes: number;
  topic: string;
  lede: string;
  blocks: Block[];
  relatedFeature: string;
  relatedIndustry: string;
};

export const resources: Resource[] = [
  {
    slug: "traceability-requirements-iatf-16949-audit",
    title: "What an IATF 16949 auditor actually asks for on traceability",
    metaTitle: "IATF 16949 Traceability Requirements — What Auditors Ask",
    description:
      "The traceability evidence an IATF 16949 auditor asks a supplier to produce, why batch records usually fail, and what a per-unit record has to contain.",
    published: "2026-09-11",
    readingMinutes: 8,
    topic: "Audit and compliance",
    lede: "Clause references are easy to quote and not much use at 09:00 on audit day. This is what gets asked for in the room, and what a record has to contain to answer it.",
    blocks: [
      { type: "note", text: "ElectronIx is not a certification body and Trace is not certified software. This is engineering experience of what auditors ask for, not compliance advice." },
      { type: "h2", text: "The question underneath every traceability question" },
      { type: "p", text: "An auditor is testing one thing: if this part comes back from the field, can you bound the problem? Everything else — the records, the labels, the retention policy — is instrumentation for that single question. When a supplier fails a traceability finding it is almost never because a document was missing. It is because the answer to \"which other units are affected\" was an estimate." },
      { type: "h2", text: "What gets asked for, in order" },
      { type: "ol", items: [
        "Pick a finished unit at random from stock. Show me its build record.",
        "Show me the components that went into it, by lot or serial, and where those lot numbers are recorded.",
        "Show me the process parameters that were specified for it, and the values actually captured.",
        "Show me who performed that operation and evidence that they were qualified to.",
        "Now go the other way. Here is a component lot. Which finished units contain it, and where did they go?",
        "Show me a unit that failed and was reworked. Show me the rework was authorised and the affected operations were repeated.",
        "How do I know these records have not been edited since they were captured?",
      ] },
      { type: "p", text: "Questions one to four are answerable from most systems, including a well-kept set of spreadsheets. Question five is where batch-level records fail. Questions six and seven are where nearly everybody fails." },
      { type: "h2", text: "Why batch records fail question five" },
      { type: "p", text: "A batch record ties a day's production to a set of component lots. When one of those lots is bad, the affected set is the entire batch, because the record cannot distinguish within it. If you build 400 units a day and the bad lot was consumed by 60 of them, a batch record forces you to contain 400." },
      { type: "p", text: "That is not a documentation problem, it is a cost problem, and it recurs every time. The fix is to record consumption at the unit, at the operation that consumed it." },
      { type: "h2", text: "What a per-unit record has to contain" },
      { type: "table", caption: "Minimum content of a defensible unit record", head: ["Element", "Why the auditor wants it"], rows: [
        ["Unique unit identity, on the part", "Without it, the record and the object cannot be connected in the field"],
        ["Job card and product revision", "Ties the unit to the specification that applied at the time"],
        ["Every component lot or serial consumed, with the operation", "The forward trace depends on it"],
        ["Captured process values with the limits that applied", "A value without its limit proves nothing"],
        ["The instrument that produced each reading", "Lets you bound a containment when an instrument drifts"],
        ["Operator identity and qualification", "Clause 7.2 competence, evidenced per operation"],
        ["Rework and repair history, including what was invalidated", "A rework loop that is invisible in the record is a finding"],
        ["Evidence of integrity", "Answers question seven"],
      ] },
      { type: "h2", text: "Question six: rework that stays visible" },
      { type: "p", text: "A common failure is a system that lets an operator redo a failed operation so the record shows only the passing result. That is a record of what you wish had happened. What an auditor wants to see is the failure, the authorisation to rework, which operations were invalidated by it, and those operations being performed again." },
      { type: "p", text: "In Trace a rework path names the operation the unit returns to and the operations whose completion is voided by it. Those operations must be performed again before the unit can advance, and both attempts stay in the record." },
      { type: "h2", text: "Question seven: proving the record was not edited" },
      { type: "p", text: "This is the question most systems answer with \"we have user permissions\", which is an answer about access control, not integrity. It does not cover anyone with database access, and auditors know it." },
      { type: "p", text: "A stronger answer has two parts. First, the records are append-only, enforced by the database rather than by application code, so there is no code path — and no SQL prompt — that updates or deletes a captured measurement. Second, each record carries a hash of the one before it, forming a chain per unit. Altering a historical row breaks every link after it, and the chain can be recomputed on demand." },
      { type: "p", text: "Corrections still have to be possible, because readings do genuinely get recorded against the wrong unit. The correct shape is a new row that supersedes the old one, carrying a reason and the operator who authorised it, with the original left in place. An auditor who sees corrections handled that way trusts the rest of the record more, not less." },
      { type: "h2", text: "Practical preparation" },
      { type: "ul", items: [
        "Pick three finished units from stock yourself and walk questions one to seven. Time it. If any answer takes more than a few minutes, that is your finding waiting to happen.",
        "Pick a component lot from a supplier invoice and try the forward trace cold. Most plants discover here that the lot number was never captured at the station.",
        "Check that your captured values carry the limits that applied at the time, not today's limits. Specifications change.",
        "Check that a reworked unit's record shows the failure, not just the eventual pass.",
      ] },
    ],
    relatedFeature: "audit-and-tamper-evidence",
    relatedIndustry: "auto-components",
  },
  {
    slug: "capturing-torque-data-from-a-plc",
    title: "Capturing torque data from a PLC over RS485 without losing readings",
    metaTitle: "Capturing Torque Data From a PLC Over RS485 — Field Notes",
    description:
      "Getting per-fastener torque values off a controller into a traceability record: polling versus push, timestamps, raw payloads and what loses data.",
    published: "2026-09-11",
    readingMinutes: 9,
    topic: "Machine integration",
    lede: "Getting a number out of a torque controller is easy. Getting every number, tied to the right unit, with a timestamp you can defend, is the actual job.",
    blocks: [
      { type: "h2", text: "The reading is not the hard part" },
      { type: "p", text: "Most torque controllers will happily give you a value over RS232, RS485 or Ethernet. Some push a line of ASCII after every fastener, some expose a register you poll, some write to a folder. Any of those can be read in an afternoon." },
      { type: "p", text: "What takes the other three weeks is everything around it: which unit the reading belongs to, what happens when the reading arrives twice, what happens when it does not arrive at all, and what you do with a reading whose timestamp disagrees with the station's." },
      { type: "h2", text: "Poll or be pushed" },
      { type: "table", caption: "Two integration shapes and what each costs", head: ["Shape", "Good", "Bad"], rows: [
        ["Push — controller sends a line after each fastener", "You get every rundown, including the ones the operator repeated", "You must buffer; a station busy elsewhere can miss a line"],
        ["Poll — read a result register on a cycle", "Simple, stateless, survives restarts", "Two rundowns inside one poll interval and you lose one"],
        ["File drop — controller writes a result file", "Durable, survives a station reboot", "Partial files; you must wait for an atomic rename, never read on create"],
      ] },
      { type: "p", text: "If you can choose, choose push with a durable local buffer. The failure mode you cannot recover from is a rundown that happened and was never recorded, because the operator has already moved the part." },
      { type: "h3", text: "Polling faster is not the fix" },
      { type: "p", text: "The instinct on a missed rundown is to shorten the poll interval. On a four-fastener operation with a fast gun, the interval you would need is smaller than the controller's own update rate, and you will start reading the same value twice instead. Sequence numbers, not speed, are what distinguish two identical rundowns." },
      { type: "h2", text: "Binding a reading to a unit" },
      { type: "p", text: "A torque value with no unit attached is telemetry, not traceability. Three bindings, in descending order of reliability:" },
      { type: "ol", items: [
        "The station knows which unit is in the fixture because it was scanned at the start of the operation, and readings arriving during that operation belong to it. This is the only one that is reliable, and it is why the identity gate exists.",
        "The controller is told the unit identity and echoes it back with the reading. Good when supported, uncommon below the enterprise tier.",
        "Correlate by timestamp alone. Do not do this. Two stations, one clock drift and your record is confidently wrong.",
      ] },
      { type: "h2", text: "RS485 specifics that bite" },
      { type: "ul", items: [
        "Termination and biasing. An unterminated multidrop segment works fine on a bench and fails intermittently on a shop floor with a VFD running. Intermittent is worse than broken, because you will not notice the missing readings.",
        "Half duplex means you must not transmit while a response is inbound. A driver that fires a poll on a timer regardless of state will collide with itself under load.",
        "Address collisions on a multidrop segment produce plausible readings from the wrong instrument. Enumerate and record device addresses as configuration, and record which device produced each reading.",
        "Cable routing beside a servo drive will give you framing errors in bursts. Log framing errors as a counter you can see, or you will be debugging the software for a week.",
      ] },
      { type: "h2", text: "Store the raw bytes" },
      { type: "p", text: "Whatever the controller sends, store it verbatim beside the parsed value. It costs a text column and it settles arguments." },
      { type: "code", caption: "A raw payload kept next to the parsed reading", lines: [
        "point       final_torque",
        "value       12.1 Nm          limits 10.0 - 14.0, nominal 12.0",
        "verdict     PASS",
        "source      DEVICE           device TW-01",
        "raw         TQ,12.10,NM,OK\\r\\n",
        "recorded_at 2026-08-18T06:23:41+05:30   (device clock)",
        "received_at 2026-08-18T06:23:41+05:30   (server clock)",
      ] },
      { type: "p", text: "Two years later, when a customer's engineer says the value looks rounded, the raw line is the answer. A parser that normalises before storing has thrown away the only evidence that mattered." },
      { type: "h2", text: "Two clocks, always" },
      { type: "p", text: "Record the device's timestamp and the server's, and keep both. When they disagree beyond a threshold, flag the row rather than dropping it — you never discard production data over a clock problem, you mark it so it can be seen later." },
      { type: "p", text: "A panel PC with a dead RTC battery is common and quietly corrosive: it boots to an epoch date, every reading that shift is stamped wrong, and nobody notices until an audit. A flag on the row is what makes that visible." },
      { type: "h2", text: "What to do when the instrument is unplugged mid-shift" },
      { type: "p", text: "It will happen. The correct behaviour is not to crash the station and not to block forever. Reconnect with a backoff, give every read a deadline, and let the operator continue with manual entry against the same limits — a manual reading with a manual source flag is far better than a hole in the record." },
      { type: "p", text: "That last point is worth stating plainly: a traceability system that stops the line when an instrument fails will be switched off within a month." },
    ],
    relatedFeature: "process-data-capture",
    relatedIndustry: "pumps-and-valves",
  },
  {
    slug: "what-a-part-genealogy-record-must-contain",
    title: "What a part genealogy record must contain",
    metaTitle: "What a Part Genealogy Record Must Contain — Field Guide",
    description:
      "The structure of a genealogy record that answers both trace directions, and the one modelling mistake that quietly breaks your recall query.",
    published: "2026-09-11",
    readingMinutes: 7,
    topic: "Data modelling",
    lede: "Most genealogy implementations answer the backward question well and the forward question badly. The cause is almost always one modelling decision made early.",
    blocks: [
      { type: "h2", text: "Two questions, not one" },
      { type: "p", text: "Backward: given this unit, what went into it? Forward: given this component, which units contain it? They sound symmetrical and they are not, because the backward query walks a tree you already have a handle on, and the forward query searches for it." },
      { type: "p", text: "A design that only anticipates the backward query produces a record that is perfectly readable per unit and unusable during a containment." },
      { type: "h2", text: "The mistake that breaks recall" },
      { type: "p", text: "Storing consumed components as a JSON blob on the unit. It is convenient, it renders nicely, and it makes the forward query a full scan with a text match. That is fine at ten thousand units and unusable at two million, which is roughly four years of a modest line." },
      { type: "p", text: "Consumption belongs in its own rows, one per component, indexed on the lot code and on the child serial. The forward query then becomes a lookup." },
      { type: "h2", text: "Serialised children and lots are different things" },
      { type: "table", caption: "Two kinds of genealogy link", head: ["", "Serialised child", "Lot consumption"], rows: [
        ["What is recorded", "The child unit's own identity", "A lot code and a quantity"],
        ["Has its own history", "Yes — full sub-tree", "No — the lot is external"],
        ["Forward query", "Child serial → parent units", "Lot code → all units that consumed it"],
        ["Typical example", "Stem sub-assembly built on your line", "Gasket batch from a supplier"],
      ] },
      { type: "p", text: "Modelling both as one nullable pair of columns, with a constraint that exactly one is populated, keeps the two forward indexes separate and the query planner honest. Collapsing them into one text column labelled \"component\" is what forces a scan later." },
      { type: "h2", text: "Depth is part of the record" },
      { type: "p", text: "If a sub-assembly is serialised and built on your line, it carries its own genealogy, and the parent inherits the whole tree. An auditor will ask how deep the record goes, so the answer should be visible rather than inferred." },
      { type: "p", text: "Cap the walk depth in the query. A cycle in genealogy data should be impossible — a unit cannot be its own component, and that is worth a database constraint rather than a code comment — but an unbounded recursive walk on bad data will take a production database down, and the fix is a bound, not optimism." },
      { type: "h2", text: "What every link must carry" },
      { type: "ul", items: [
        "The parent unit and the component, as above.",
        "The BOM line it satisfies. Without it you cannot tell a legitimate substitution from a mis-build.",
        "The operation sequence it was consumed at. \"Which operation fitted the bad bearing\" is a real question during containment.",
        "The station and the operator. Sometimes the pattern is one operator on one shift.",
        "Both timestamps — device and server — like every other evidence row.",
        "A quantity, for lot links. Consuming 2 of a lot and 200 of it are different exposures.",
      ] },
      { type: "h2", text: "The second forward axis people forget" },
      { type: "p", text: "Component lots are not the only thing that goes wrong. An instrument drifts, a fixture wears, a machine runs out of calibration between Tuesday's check and Thursday's. The question is then \"which units did this device touch in this window\", and it is not a genealogy query at all — it is a measurement query, and it needs its own index on device and time." },
      { type: "p", text: "Systems that record only that a scan happened at a station cannot answer it. Recording which instrument produced each reading is what makes it a lookup." },
      { type: "h2", text: "A test worth running on any system you are evaluating" },
      { type: "ol", items: [
        "Ask the vendor to show a forward trace from a lot code on a dataset with at least a million units, and watch the clock.",
        "Ask them to show the same query by instrument and time window.",
        "Ask what happens to the record when a component is substituted with an approved alternate.",
        "Ask to see a unit whose sub-assembly was reworked, and check whether the sub-assembly's own history is still attached.",
      ] },
    ],
    relatedFeature: "part-genealogy",
    relatedIndustry: "switchgear-and-electricals",
  },
  {
    slug: "laser-marking-vs-label-printing",
    title: "Laser marking or label printing for traceability",
    metaTitle: "Laser Marking vs Label Printing for Traceability",
    description:
      "How to choose between a printed label and a direct part mark: process survival, readability, cost per station, and the scanner mistake that sinks DPM projects.",
    published: "2026-09-11",
    readingMinutes: 7,
    topic: "Marking",
    lede: "Both are legitimate. The decision is made by your process, not by preference, and the expensive mistake is in the scanner budget rather than the marker.",
    blocks: [
      { type: "h2", text: "Start with what the part goes through" },
      { type: "p", text: "Identity has to survive from the operation it is applied at to the last time anyone needs to read it — which, for a warranty claim, is years after dispatch and in someone else's workshop." },
      { type: "table", caption: "What kills a mark", head: ["Process step", "Printed label", "Laser DPM"], rows: [
        ["Wash / degrease", "Usually fails", "Survives"],
        ["Paint or powder coat", "Fails, or must be re-applied after", "Survives if applied post-coat, obscured if pre"],
        ["Heat treatment", "Fails", "Survives on most substrates"],
        ["Handling and stacking", "Abrades, peels at edges", "Survives"],
        ["Field life, years outdoors", "Adhesive fails", "Survives"],
        ["Cost per station", "Low — one printer serves a line", "High — marker plus DPM scanners"],
      ] },
      { type: "h2", text: "The rule that decides it" },
      { type: "p", text: "If the part goes through wash, paint or heat after identity is applied, you need a direct part mark. If it does not, a printed label is the cheaper, faster and more flexible answer, and choosing a laser anyway is spending money on a problem you do not have." },
      { type: "h2", text: "Data Matrix, not QR, for direct marking" },
      { type: "p", text: "For DPM the code should be a Data Matrix. It is more robust at small sizes, has better error correction per unit area, and reads reliably at low contrast — which is exactly what a laser mark on bare metal is. QR is the right choice on a printed label where contrast is high and a phone camera may be the reader." },
      { type: "h2", text: "The scanner mistake" },
      { type: "p", text: "This is the one that sinks projects. An ordinary 1D or general-purpose 2D scanner will not reliably read a laser mark on bare metal. Reading a DPM code needs an imager with appropriate illumination: diffuse dome lighting for shiny or curved surfaces, low-angle for etched flat surfaces." },
      { type: "p", text: "Budgeting an inexpensive scanner per station and discovering this at commissioning is the classic failure in these projects. If you are marking at operation 1, every station downstream that reads identity needs a DPM-capable imager — and that is a per-station cost, not a one-off." },
      { type: "h2", text: "Mark quality is measurable, so measure it" },
      { type: "p", text: "A mark that reads today on a new scanner and fails in two years on a customer's reader was never a good mark. Grade the mark on application and record the grade. When grades start drifting, the laser needs attention before you start losing readability in the field." },
      { type: "p", text: "Read the mark back and verify it matches the intended identity before the unit is allowed to advance. A mark that was applied but never verified is a unit with an identity nobody has confirmed." },
      { type: "h2", text: "Mixed is normal" },
      { type: "p", text: "Plenty of plants run both: a direct mark on the raw part at the first operation so identity survives the process, and a printed label at dispatch carrying the customer's required format, barcode symbology and branding. These are not competing decisions — one is identity, the other is documentation." },
      { type: "p", text: "What matters is that both are generated from the same binding, so the identity on the part can never disagree with the identity in the record." },
      { type: "h2", text: "Practical checklist before you buy a marker" },
      { type: "ul", items: [
        "Confirm the substrate and whether the mark is applied before or after any coating.",
        "Get a sample marked on your actual material, then read it with the scanner you intend to buy — not the vendor's demo scanner.",
        "Confirm cycle time. A mark that takes eight seconds on a twelve-second takt is a line balance problem.",
        "Confirm the interface. A file-drop interface must use an atomic rename, or you will read half-written files.",
        "Price the DPM imagers for every downstream station before approving the marker.",
      ] },
    ],
    relatedFeature: "marking-and-labels",
    relatedIndustry: "precision-machining",
  },
  {
    slug: "planning-a-recall-scope-calculation",
    title: "Planning a recall scope calculation before you need one",
    metaTitle: "How to Plan a Recall Scope Calculation in Manufacturing",
    description:
      "How to bound a containment when a component lot goes bad, and why proving units clean matters as much as finding the affected ones.",
    published: "2026-09-11",
    readingMinutes: 8,
    topic: "Quality operations",
    lede: "A recall is not the time to discover what your records cannot answer. Run the query now, on a lot you chose at random, and find out.",
    blocks: [
      { type: "h2", text: "The clock starts before you are ready" },
      { type: "p", text: "Containment typically starts with a phone call from a supplier or a customer naming a lot code and a date range. From that moment you are being measured on two things: how fast you can bound the affected set, and how confident you are in the boundary." },
      { type: "p", text: "Most plants can eventually produce a list. The cost is in \"eventually\", and in how much clean production gets contained alongside the bad." },
      { type: "h2", text: "Proving units clean is half the value" },
      { type: "p", text: "The instinct is that a recall query finds affected units. In practice the money is in the other half: proving which units are demonstrably clean so they can keep shipping." },
      { type: "p", text: "If your record cannot distinguish within a day's production, every unit built that day is contained. On a 400-a-day line where 60 units actually consumed the lot, that is 340 units held for no reason — and it recurs every single time." },
      { type: "h2", text: "What has to be captured beforehand" },
      { type: "table", caption: "Capture these or the query cannot be answered", head: ["Capture", "What it lets you bound"], rows: [
        ["Lot code at the operation that consumed it", "Which units contain the lot — the primary question"],
        ["Quantity consumed per unit", "Exposure, when partial consumption matters"],
        ["Which instrument produced each reading", "Containment by drifted machine, a separate axis entirely"],
        ["Build timestamp per unit", "The containment window, so you can bound rather than guess"],
        ["Dispatch record and customer", "Who has to be notified, and how many each"],
        ["Unit state", "Which affected units are still in your building and can be pulled today"],
      ] },
      { type: "p", text: "The one most often missing is the second: quantity. The one most often missing entirely is the third." },
      { type: "h2", text: "Sizing the query honestly" },
      { type: "p", text: "A forward trace from a lot code should be an indexed lookup. If a vendor demonstrates it on a thousand units, ask what it does on two million, because that is roughly four years of a modest line and the answer changes completely if consumption is stored as a JSON blob." },
      { type: "h2", text: "The second axis: containment by machine" },
      { type: "p", text: "Not every containment starts with a supplier lot. A torque gun drifts, a gauge loses calibration, a fixture wears. The question becomes: which units did this device touch between the last good calibration check and now?" },
      { type: "p", text: "This is not a genealogy query. It needs the instrument recorded against each reading and an index on device and time. Systems that record only scan events cannot answer it at all, which means every containment of that kind falls back to a date range and over-contains." },
      { type: "h2", text: "Run the drill" },
      { type: "ol", items: [
        "Take a component lot code from a supplier invoice, at random, from four months ago.",
        "Without warning anyone, ask for the list of finished units that consumed it, the customers they went to, and the build window.",
        "Time it. Write the time down.",
        "Now ask for the list of units from the same period that provably did not consume it.",
        "Repeat with an instrument and a two-hour window.",
      ] },
      { type: "p", text: "Whatever that drill costs you in an afternoon, it is a fraction of what the same gap costs during a live containment. Most plants that run it for the first time find that step four is the one nobody can answer." },
      { type: "h2", text: "What the output should look like" },
      { type: "p", text: "A containment report that is actually usable names: the affected unit identities and serials, the customer each shipped to, the build window from first to last, how many are still in your building, and how many are provably clean. A count on its own is not a containment plan." },
    ],
    relatedFeature: "recall-and-forward-trace",
    relatedIndustry: "auto-components",
  },
  {
    slug: "mes-or-standalone-traceability",
    title: "MES or standalone traceability: choosing without over-buying",
    metaTitle: "MES or Standalone Traceability — How to Choose",
    description:
      "When a full MES is the right answer, when standalone traceability is, and the questions that separate the two for a mid-size manufacturer.",
    published: "2026-09-11",
    readingMinutes: 8,
    topic: "Buying",
    lede: "The honest version of this comparison is not which is better. It is which problem you have, and whether you can afford the one that solves more of them.",
    blocks: [
      { type: "h2", text: "What an MES is actually for" },
      { type: "p", text: "An MES coordinates production: scheduling, dispatching work, tracking WIP, measuring OEE, managing resources, and — usually as one module among many — traceability. If your problem is that you do not know what your plant is doing right now, an MES is the correct category." },
      { type: "p", text: "If your problem is that a customer asked for the build record of a part from March and you could not produce it, an MES will solve that, and about eleven other things you did not ask for, at a price that reflects all twelve." },
      { type: "h2", text: "The question that separates them" },
      { type: "p", text: "Ask what is actually failing today. Not what would be nice — what is costing money now." },
      { type: "table", caption: "Symptom to category", head: ["What is failing", "Category"], rows: [
        ["Cannot answer which units contain a bad component lot", "Traceability"],
        ["Cannot produce process values for a warranty claim", "Traceability"],
        ["Customer audit raised a traceability finding", "Traceability"],
        ["Do not know which orders are where on the floor", "MES"],
        ["Cannot measure or improve OEE", "MES"],
        ["Scheduling is a whiteboard and it is wrong by noon", "MES / APS"],
        ["Quality records exist but live in twelve spreadsheets", "Traceability or QMS"],
      ] },
      { type: "h2", text: "The over-buying pattern" },
      { type: "p", text: "A traceability finding from a customer audit arrives with a deadline. The plant evaluates MES suites because that is what the search returns, gets quotes that are a multiple of the budget, and the project stalls. Eighteen months later the finding is still open and the spreadsheets are still there." },
      { type: "p", text: "The alternative is not a worse version of an MES. It is a system that does traceability properly and does not pretend to schedule your plant." },
      { type: "h2", text: "The under-buying pattern" },
      { type: "p", text: "The opposite failure is real too. A plant that genuinely needs production visibility buys a barcode scanning project, gets traceability, and still cannot answer where anything is. Six months later it buys the MES anyway and now runs two systems." },
      { type: "p", text: "If more than two rows in the MES column above are true for you, buy the MES." },
      { type: "h2", text: "Can they coexist?" },
      { type: "p", text: "Yes, and this is the common end state for a plant that grows. The thing to check is whether the traceability system will still own its data when the MES arrives, or whether adopting the MES means migrating the traceability record into it." },
      { type: "p", text: "The practical test: does the traceability system keep its own database with a clean boundary, and can the MES become the source of work orders without a data migration? If the answer is yes, starting with traceability is not a decision you have to undo." },
      { type: "h2", text: "Questions worth asking either kind of vendor" },
      { type: "ul", items: [
        "What does a station do when the server is unreachable? Listen for whether capture continues, or only \"it reconnects\".",
        "What happens to production if our subscription lapses or the licence file expires?",
        "Show me a forward trace from a lot code on a realistic dataset. Time it.",
        "Can records be edited after capture, and how would I prove they had not been?",
        "What does it take to change a torque limit — a configuration change, or a release?",
        "Who will be on site in week one, and who answers the phone in month six?",
      ] },
      { type: "p", text: "The last one decides more implementations than the feature matrix does." },
    ],
    relatedFeature: "deployment-and-updates",
    relatedIndustry: "general-assembly",
  },
];

export const resourceSlugs = resources.map((r) => r.slug);

export function resourceBySlug(slug: string): Resource | undefined {
  return resources.find((r) => r.slug === slug);
}
